### ISSUE TITLE
Utils doesn't start up

### ISSUE THREAD

**Issue by Telesphoreo** [Adaptified/Utils#1]
`[20:36:35 ERROR]: Could not load 'plugins/Utils.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/pravian/bukkitlib/implementation/BukkitPlugin
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: net/pravian/bukkitlib/implementation/BukkitPlugin
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_45]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_45]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_45]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_45]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_45]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_45]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_45]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_45]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.pravian.bukkitlib.implementation.BukkitPlugin
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_45]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_45]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_45]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_45]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_45]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_45]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_45]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_45]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-6c9b0a1-de5c261]
    ... 6 more`

**Comment by mgejay** [comment]
I don't know what you are doing but it starts for me. I will look into this.

**Comment by mayokek** [comment]
@Adaptified, you are missing the build.xml on GitHub.
It won't load up without build.xml (It can, but it will be simply Java (not BukkitLib))

**Comment by mgejay** [comment]
Ahh, ok @AvalancheYT.

**Comment by mgejay** [comment]
Closed in Utils Remastered commit.
